general = {disable_mod = false, hide_bossbar = true, shadow_text = true, auto_start = false, animationSpeed = 1.2, always_show_ping = false, hide_debug_crosshair = false, background_color = 16777215, space_modules = true, always_show_profiler = false, animations = true, fontScale = 1.0, hide_sidebar = true, always_show_tps = false}
[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	lines = {opengl_version = true, allocation_rate = true, display = true, java_version = true, gpu_driver = true, memory_usage = true, allocated_memory = true, cpu = true, gpu_utilization = true, time = true, gpu = true}
	enabled = true

[[modules_left]]
	color_high = 5635925
	color_med = 16777045
	name = "fps"
	lines = {fps = true}
	enabled = true
	color_low = 16733525
[[modules_left]]
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	name = "coords"
	name_color = 16733525
	lines = {chunk_coords = false, player_coords = true, block_coords = true, absolute_velocity = false, velocity = true, chunk_relative_coords = true, horizontal_velocity = false}
	enabled = true
[[modules_left]]
	name = "graphics"
	name_color = 16755200
	value_color = 5636095
	lines = {shader = true, render_distance = true, graphics = true, clouds = true, biome_blend_radius = false}
	enabled = true
[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	lines = {light = true, biome = true, rotation = false, facing = true, slime_chunk = true, local_difficulty = false, day_ticks = false, days_played = true, dimension = false, highest_block = false, highest_block_server = false, light_server = false}
	enabled = true
